# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2be7fdf9051a864d9d1f618bb758f2d118b9d894a8d03828702a3c56d0dc6c31a07f4f7ef2077acc46696987fb8254b9f6ffd9c20197308f27e48468bf33ad5

test:
  secret_key_base: 90155c36769b73a41cdb75f053336b0c97b9640958129e8d6f7af08914051fbb6fb901e66369b537a982b877f64765899ef88b179ddd5584f5558b588d52f713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
